import { GetStaticProps } from "next";
import Image from "next/image";
import Head from "next/head";
import styles from "../styles/home.module.css";
import db from "@/services/firebaseConnection";
import { collection, getDocs } from "firebase/firestore";

import heroImage from "/public/hero.png";

interface HomeProps {
	tasks: number;
	comments: number;
}

export default function Home({ tasks, comments }: HomeProps) {
	return (
		<>
			<div className={styles.container}>
				<Head>
					<title>Tarefas+ | Organize e compartilhe suas tarefas.</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main className={styles.main}>
					<div className={styles.logoContent}>
						<Image
							className={styles.hero}
							src={heroImage}
							alt="Taskify"
							priority
						/>
					</div>
					<h1 className={styles.title}>
						Sistema feito para você organizar
						<br />e compartilhar suas tarefas.
					</h1>

					<div className={styles.infoContent}>
						<section className={styles.box}>
							<span>+{tasks} posts</span>
						</section>
						<section className={styles.box}>
							<span>+{comments} comentários</span>
						</section>
					</div>
				</main>
			</div>
		</>
	);
}

export const getStaticProps: GetStaticProps = async () => {
	const commentRef = collection(db, "comments");
	const taskRef = collection(db, "tasks");

	const commentSnapshot = await getDocs(commentRef);
	const taskSnapshot = await getDocs(taskRef);

	return {
		props: {
			tasks: taskSnapshot.size || 0,
			comments: commentSnapshot.size || 0,
		},
		revalidate: 60, // 1 minuto
	};
};
