import Head from "next/head";
import styles from "@/styles/home.module.css";
import Image from "next/image";

import heroImage from "/public/hero.png";

export default function Home() {
	return (
		<>
			<div className={styles.container}>
				<Head>
					<title>Tarefas+ | Organize e compartilhe suas tarefas.</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main className={styles.main}>
					<div className={styles.logoContent}>
						<Image
							className={styles.hero}
							src={heroImage}
							alt="Tarefas+"
							priority
						/>
					</div>
					<h1 className={styles.title}>
						Sistema feito para você organizar
						<br />e compartilhar suas tarefas.
					</h1>

					<div className={styles.infoContent}>
						<section className={styles.box}>
							<span>+12 posts</span>
						</section>
						<section className={styles.box}>
							<span>+90 comentários</span>
						</section>
					</div>
				</main>
			</div>
		</>
	);
}
